package org.example.Tools;

import org.example.MyCollection.DataClasses.Entity;
import org.example.MyStream.InputHandler;
import org.example.MyStream.OutputHandler;
import org.example.MyStream.fileStream.FileInputHandler;
import org.example.Tools.Validators.Validator;

import java.io.IOException;
import java.util.HashMap;

public class ObjectBuilder {
    InputHandler inputHandler;
    OutputHandler outputHandler;
    private int errCounter = 0;



    /**
     * custom-streams constructor
     * @param inputHandler input stream
     * @param outputHandler output stream
     */
    public ObjectBuilder(InputHandler inputHandler, OutputHandler outputHandler){
        this.inputHandler = inputHandler;
        this.outputHandler = outputHandler;
    }

    /**
     * create new object by user-dialogue
     * @param tree object tree by ObjTree class
     * @return new object
     */
    public <T extends Entity> T buildDialogue(ObjectReflect tree) {
        return buildDialogue(tree, null);
    }

    public <T extends Entity> T buildDialogue(ObjectReflect tree, T oldObj) {
        outputHandler.println(tree.getFields().size() + "");
        T obj = (T) tree.constructor.get();
        HashMap<String, Object> values = new HashMap<>();

        for (ObjectReflect field : tree.getFields()) {
            try {
                if (field.isAutoGenerated()) {
                    if(oldObj!=null) values.put(field.getFieldName(), oldObj.getValues().get(field.getFieldName()));
                    continue;
                }

                if (!field.isPrimitive()) {
                    if (field.isMayNull() && askForSkip(field.getFieldName())) {
                        if(oldObj!=null) values.put(field.getFieldName(),(T) oldObj.getValues().get(field.getFieldName()));
                        values.put(field.getFieldName(), null);
                    }
                    else {
                        System.out.println("Сектор " + field.getFieldName());
                        if(oldObj!=null) values.put(field.getFieldName(), buildDialogue(field, (T) oldObj.getValues().get(field.getFieldName())));
                        else values.put(field.getFieldName(), buildDialogue(field));

                    }
                    continue;
                }

                while (true) {
                    System.out.print("Введите " + field.getFieldName() + " (" + field.getFieldType() + ")");
                    if(oldObj!=null) {
                        System.out.println(" prev= " + oldObj.getValues().get(field.getFieldName()));
                        System.out.print("Чтобы оставить старое значение нажмите Enter");
                    }
                    System.out.println();

                    if (field.isEnum()) {
                        outputHandler.print("\t" + "Возможные значения: ");
                        for(Object o : field.getEnumContains().values()) outputHandler.print(o + " ");
                        outputHandler.println(" ");
                    }
                    //System.out.println("DEBUG : ожидаю команду от " + inputHandler.getClass().getSimpleName());
                    String value = inputHandler.get();
                    if(isFile()) outputHandler.println("> " + value);
                    //System.out.println("DEBUG: \'" + value+"\'");

                    if(value.strip().equals("")) {

                        if(oldObj!=null){
                            values.put(field.getFieldName(), oldObj.getValues().get(field.getFieldName()));
                            break;
                        }
                        else if (field.isMayNull()){
                            values.put(field.getFieldName(), Converter.convert(field.getFieldType(), null));
                            break;
                        }

                    }

                    try {
                        values.put(field.getFieldName(), isValid(field, value));
                        break;
                    }  catch (IllegalArgumentException e) {
                        System.out.println("Вы ввели недопустимое значение! " + e.getMessage() + ". Повторите ввод");
                        if(isFile()) break;
                    }
                }
            }
            catch ( IOException e) {
                System.out.println(e.getMessage());//e.printStackTrace();
            }
        }
        obj.init(values);
        return (T) obj;
    }

    /**
     * Build object by values string-map
     * @param tree object tree by ObjTree class
     * @param data values string-map
     * @return new object
     */
    public <T extends Entity> T buildByStringMap(ObjectReflect tree, HashMap<String, String> data) {
        T obj = (T) tree.constructor.get();
        HashMap<String, Object> values = new HashMap<>();

        for (ObjectReflect field : tree.getFields()) {
            try{
                if (!field.isPrimitive()) {
                    HashMap<String, String> buffData = new HashMap<>();
                    boolean nullFlag = true;
                    for(String key: data.keySet()){
                        if(key.contains(field.getFieldName())) {
                            buffData.put(key.substring(field.getFieldName().length() + 1), data.get(key));
                            if (data.get(key) != null) nullFlag = false;
                        }
                    }
                    if(nullFlag) values.put(field.getFieldName(), null);
                    else values.put(field.getFieldName(), buildByStringMap(field, buffData));
                    continue;
                }

                values.put(field.getFieldName(), isValid(field, data.get(field.getFieldName())));
            } catch (Exception e) {
                outputHandler.println("Error while input by string: " + e.getMessage());
            }
        }
        obj.init(values);
        return (T)obj;
    }

    /**
     * protector-func for stop loop entering
     * @return flag to stop
     */
    private boolean dumbUserProtection(){
        errCounter++;
        if(errCounter>20 || isFile()){
            return true;
        }
        return false;
    }

    /**
     * answer user for skip this field
     * @param name field name
     * @return flag to skip
     */
    private boolean askForSkip(String name) throws IOException {
        String ans;
        outputHandler.println("Поле " + name + " не обязательное, пропустить? (Y/N)");
        while (true){
            ans = inputHandler.get().trim().toUpperCase();
            if(ans.equals("N") || ans.equals("Y")) break;
            else {
                outputHandler.printErr("Разве \"" + ans + "\" похоже на Y/N ??, попробуйте еще раз");
                if(dumbUserProtection()) return false;
            }
        }
        return ans.equals("Y");
    }

    /**
     * Check is entered value are valid
     * @param field target field
     * @param value entered value
     * @return validated value
     * @throws IllegalArgumentException
     */
    private Object isValid(ObjectReflect field, String value) throws IllegalArgumentException {
        if(field.isEnum()) {
            if(field.getEnumContains().containsKey(value)) {
                return field.getEnumContains().get(value);
            } else {
                throw new IllegalArgumentException("Не существующая константа");
            }
        } else {
            if (field.getValidators() != null) {
                Validator.validate(value, field.getValidators());

            }
            return Converter.convert(field.getFieldType(), value);
        }
    }

    /**
     * is this script-executing??
     * @return boolean flag
     */
    private boolean isFile(){
        return inputHandler.getClass() == FileInputHandler.class;
    }
}